spring:
  application:
    name: drugstore
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
#          model: gpt-4o
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB

# sms settings
sms:
  settings:
    sid: ${TWILIO_ACCOUNT_SID}
    token: ${TWILIO_AUTH_TOKEN}
    phone-number: ${TWILIO_PHONE_NUMBER}

logging:
  level:
    root: info
