DROP TABLE IF EXISTS DrugsInfo;

CREATE TABLE DrugsInfo
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255) NOT NULL,
    expiration_date date         NOT NULL,
    form            varchar(255),
    category        varchar(255),
    md5 varchar(32) NOT NULL
);
