DROP TABLE IF EXISTS DrugsInfo;
DROP TABLE IF EXISTS DrugsSourceDigest;

CREATE TABLE DrugsInfo
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255) NOT NULL,
    expiration_date date         NOT NULL,
    form            varchar(255) NOT NULL,
    category        varchar(255)
--     PRIMARY KEY (id)
);

CREATE TABLE DrugsSourceDigest
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    md5 varchar(32) NOT NULL,
    drug_id int REFERENCES DrugsInfo(id) NOT NULL
)
